# Update static resources on page reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
# Configuring Port
server.port = 8081
# Database
spring.datasource.url=jdbc:h2:tcp://localhost/~/test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none